#!/usr/bin/env bash
# filename: bash_profile   (linked from ~/.bash_profile)
# purpose: For setting login-shell configs, both non-interactive & interactive.


# Note: This config file is executed automatically by bash for login shells
#   but not non-login shells.


# Non-BASH-specific login-shell-specific configs are in ~/.profile
source ~/.profile

# BASH-specific login-shell-specific configs are in ~/.bash_login
# (However, currently I don't have any need for login-shell-specific configs.)
# If `~/.bash_login` exists (which it doesn't) & is readable, source/execute it.
if [[ -r ~/.bash_login ]] ; then source ~/.bash_login ; fi

# BASH-specific interactive-shell configs are in ~/.bashrc
# If the (login) shell is interactive, source/execute `~/.bashrc`.
if [[ $- == *i* ]] ; then
    source ~/.bashrc ;
fi

