#!/usr/bin/env bash
# filename: bashrc_etc   (linked from ~/.bashrc_etc)
# purpose: Set interactive-shell configs not already set for prompt
#   and commands (functions and aliases).

# This file is sourced from ~/.bashrc (which is for interactive shells).


# make less more friendly for non-text input files, see lesspipe(1)
if [[ -x /usr/bin/lesspipe ]] ; then eval "$(SHELL=/bin/sh lesspipe)" ; fi

# command-line history
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth  # Don't save duplicates or inputs starting with space

# Use `fuck` command - for suggesting command-line mistake re-writes.
eval $(thefuck --alias)

