#!/usr/bin/env bash
# filename: bashrc_aliases_lsGNU   (linked from ~/.bashrc_aliases)
# purpose: For defining custom commands (functions and aliases) in the shell.

# This file is sourced from ~/.bashrc (which is for interactive shells).


# List Aliases
# ----------------------------------------------------------------------

# directory-content listing
# -------------------------
# Custom keys overview -- Combine these to form various list commands:
#  RE CONTENT:
#   l   list (basic list) - don't show backup or hidden files    [ l =>  list ]
#   a   show "all" hidden files (dotfiles, but not . or ..)      [ a =>  "all"]
#   aa  show all hidden files (including . and ..)               [aa =>   all ]
#   s   show backup files (ie, files ending with a tilde ~)      [ s =>  show ]
#  RE FORMAT:
#   k   show vertical list with detail/long-format               [ k => v-more]
#   j   show vertical list (w/o detail)                          [ j => v-less]
#       [k =>   up (vim key bindings) / vertical / more (detail) ]
#       [j => down (vim key bindings) / vertical / less (detail) ]
#  RE CONTENT+FORMAT:
#   f   show full detail                                         [ f =>  full ]
#       (l+f = lf equivalent to l+aa+s+k = laask)
#
# (Note: "content" refers to directory elements -- files; "format" refers to
#  changing the orientation from horizontal to vertical and inclusion or
#  exclusion of meta information, which doesn't change the shown directory file-
#  content, although it is technically another kind of displayed "content".)
#
#  POSSIBLE COMBOS:
#    list-command =  l[a|aa][s][j|k] | l[s][a|aa][j|k] | lf
#                      where [] indicates optional and | indicates "or"
#                      note: content comes first:   l[a|aa][s]  |  l[s][a|aa]
#                            & format comes last:             [j|k]

# Note: The `nullglob` option should have already been set (on) in `.bashrc_opt`
# so that list pattern-matching is silent for null matches.

# TODO: Correct this minor problem: In bash, in an empty directory (that
#       contains just `.` & `..`) `l` displays `.` and `la` displays `.`.
#       (They shouldn't display anything. `ls` correctly displays nothing.)



# Enable colors for ls, etc.  Prefer ~/.dir_colors
if [[ -x /usr/bin/dircolors ]] ; then
    if [[ -f ~/.dir_colors ]] && [[ -r ~/.dir_colors ]] ; then
	    eval `dircolors -b ~/.dir_colors`
    else
	    eval `dircolors -b /etc/DIR_COLORS`
    fi
fi
if [[ -x /usr/local/bin/gdircolors ]] ; then
    if [[ -f ~/.dir_colors ]] && [[ -r ~/.dir_colors ]] ; then
	    #eval `gdircolors -b ~/.dir_colors`
        # If this doesn't work (as it was not working originally), then might
        # want to try the following (or a more efficient version of it):
        #gdircolors -b ~/.dir_colors > temp.txt
        #source temp.txt
        #rm temp.txt
        # Trying
        source <( gdircolors -b ~/.dir_colors )
    fi
fi


# Reworking list utilities (eg `ls`), so unalias them (if they're aliased)
alias   l='' ls='' la='' lsa=''
unalias l    ls    la    lsa

alias     l=''   la=''   ls=''   las=''   laa=''   laas=''   lsa=''   lsaa=''
alias     lj=''  laj=''  lsj=''  lasj=''  laaj=''  laasj=''  lsaj=''  lsaaj=''
alias     lk=''  lak=''  lsk=''  lask=''  laak=''  laask=''  lsak=''  lsaak=''
unalias   l      la      ls      las      laa      laas      lsa      lsaa
unalias   lj     laj     lsj     lasj     laaj     laasj     lsaj     lsaaj
unalias   lk     lak     lsk     lask     laak     laask     lsak     lsaak

alias     lf=''
unalias   lf

alias   ls_=''
unalias ls_

# handle differences between GNU/Linux tools (GNU) and MacOS/Darwin tools (BSD)
if [[ `uname -s` = "Linux" ]] ; then
    alias ls_='/bin/ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
fi
if [[ `uname -s` = "Darwin" ]] ; then
    alias ls_='/usr/local/bin/gls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
fi


# basics  ( progressing from less to more )
#
alias l='ls_ -B'        #  list   - don't show backup~ files
alias lj='ls_ -1B'      #  v-less - dn/vert/less-detail
alias lk='ls_ -lhB'     #  v-more - up/vert/more-detail (long-format)
#
alias la='ls_ -AB'      #  "all" (including hidden)
alias laj='ls_ -1AB'    #  "all"  v-less
alias lak='ls_ -lhAB'   #  "all"  v-more
#
#alias ls='ls_'         #  show - show backup files (default of ls)
alias lsj='ls_ -1'      #  show   v-less
alias lsk='ls_ -lh'     #  show   v-more
#
alias las='ls_ -A'      #  "all"  show
alias lasj='ls_ -1A'    #  "all"  show   v-less
alias lask='ls_ -lhA'   #  "all"  show   v-more
#
alias laa='ls_ -aB'     #   all (including hidden)
alias laaj='ls_ -1aB'   #   all   v-less
alias laak='ls_ -lhaB'  #   all   v-more
#
alias laas='ls_ -a'     #   all   show
alias laasj='ls_ -1a'   #   all   show   v-less
alias laask='ls_ -lha'  #   all   show   v-more
#
alias lf='ls_ -lha'     #  full  =  all  show  v-more


# permutations
#
alias lsa='ls_ -A'      #  "all"  show
alias lsaj='ls_ -1A'    #  "all"  show   v-less
alias lsak='ls_ -lhA'   #  "all"  show   v-more
#
alias lsaa='ls_ -a'     #   all   show
alias lsaaj='ls_ -1a'   #   all   show   v-less
alias lsaak='ls_ -lha'  #   all   show   v-more


# saved for last
alias ls='ls_'          #  show  - show backup files (default of ls)

