#!/usr/bin/env bash
# filename: bashrc_etc_linux   (linked from ~/.config/bash/bashrc_etc_linux)
# purpose: Set interactive-shell configs not already set for opt (options),
#   prompt, and commands (functions and aliases).

# This file is sourced from ~/.bashrc (which is for interactive shells).

# pnpm
if [[ -d $HOME/.local/share/pnpm ]] ; then
  export PNPM_HOME="$HOME/.local/share/pnpm"
  case ":$PATH:" in
    *":$PNPM_HOME:"*) ;;
    *) export PATH="$PATH:$PNPM_HOME" ;;
  esac
fi
# pnpm end
