#!/usr/bin/env bash
# filename: bashrc_prompt   (linked from ~/.bashrc_prompt)
# purpose: Define the interactive-shell prompts (primary and peripheral).

# This file is sourced from ~/.bashrc (which is for interactive shells).


# PREP WORK
# ----------------------------

# Colors for the prompt
red='\e[0;31m'
RED='\e[1;31m'
green='\e[0;32m'
GREEN='\e[1;32m'
yellow='\e[0;33m'
YELLOW='\e[1;33m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m' # no color
DATE='\D{%a %b %d %k:%M}'  # format: 'Mon Feb 13 23:51'

# Set SSH indicator (on or undefined(?)/blank)
# (if variable not empty, so remotely logged in, set indicator)
if [[ -n $SSH_CLIENT ]] ; then IN_SSH=" ${BLUE}[ssh]${NC}" ; fi

# Get the IP address
# If in MacOS, use the ifconfig command
THEIP=$(uname -s | grep -i darwin > /dev/null 2>&1 && echo "$(ifconfig|grep broadcast|awk ' { print $2 }')")
#THEIP=$(type /sbin/ip > /dev/null 2>&1 && echo $(/sbin/ip route get 8.8.8.8 | awk '{print $NF; exit}'))
if [[ -z $THEIP ]] ; then
  #THEIP=$(uname -o | grep -i linux > /dev/null 2>&1 && echo "echo $(ip route get 8.8.8.8 | awk '{print $NF; exit}')")
  THEIP='IP_MISSING'
fi


# THE PROMPT VARIABLES
# ----------------------------

# See `man bash` for more info on these variables (PS0, PS1, PROMPT_COMMAND).

# Set the prompt
if [[ $(id -u) = 0 ]] ; then
  PS1="\n┌[${RED}\u${NC}] [$THEIP]${IN_SSH} [${DATE}]: ${green}\w${NC} \n└> "
else
  PS1="\n┌[${green}\u@\H${NC}] [$THEIP]${IN_SSH} [${DATE}]: ${green}\w${NC} \n└> "
fi

# Just before the prompt.
# Determine the window title (a kind of peripheral prompt):
#PROMPT_COMMAND='echo -ne "\033]0;${TERM_PROGRAM} > ${PWD##*/}\007"'
PROMPT_COMMAND='echo -ne "\e]0;${TERM_PROGRAM} - %m > ${PWD##*/}\a"'
# Bash executes PROMPT_COMMAND prior to issuing each primary prompt PS1.
#    (See .zshrc_prompt)
#    terminal_name="${TERM_PROGRAM%.*}"
#    # Getting rid of "Apple_" pre-fix from "Apple_Terminal":
#    terminal_name="${terminal_name#*_}"
#    window_title="${terminal_name} - %m : ${PWD##*/}"
#    print -Pn "\e]0;${window_title}\a"

# Just after the prompt.
PS0="\n"
# Bash displays/executes PS0 after it reads a command but before executing it.


