#!/usr/bin/env bash
# filename: bash_login   (linked from ~/.bash_login)
# purpose: Set BASH-specific login-shell-specific configs.

# No need for this file at this time.
# (I don't know of any special configs I want
#  that are BASH-specific and login-shell-specific.)
