#!/usr/bin/env sh
# filename: profile   (linked from ~/.profile)
# purpose: Set non-bash-specific configs for shells
#   (eg, `sh` or `bash` invoked as `sh`) and graphical applications(?).


# For general command-line editing (in shells and elsewhere):
# Use vi editing mode, rather than emacs mode or potentially something else.
#set -o vi  # Putting this here doesn't seem to work.


# For later reference:
# Python programming environments
#source /home/zero/.local/bin/activate.sh
#source /usr/local/bin/virtualenvwrapper_lazy.sh
#export PATH="$HOME/.pyenv/bin:$PATH"
#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"


# Need these?:
export PATH="/usr/sbin/:$PATH"
export PATH="/usr/local/sbin:$PATH" # recommended by "brew doctor" [2019-01-08]

# To include, eg, kaggle API (in MacOS)
export PATH="$HOME/.local/bin:$PATH"

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi


# WHERE ARE THESE COMING FROM (MacOS):
#/usr/local/bin
#/usr/bin
#/bin
#/usr/sbin
#/sbin
#/opt/X11/bin
#/Users/zero/.local/bin
#/usr/local/sbin


# For GNU/Linux
if [[ `uname -s` = "Linux" ]] ; then

    export PATH="$HOME/Software:$PATH"
    # Redundant?:
    #export PATH="$HOME/Software/usr/bin:$PATH"

    export MANPATH="$HOME/Software/usr/share/man:$MANPATH"
    export CPATH="$HOME/Software/usr/include:$CPATH"
    export PKG_CONFIG_PATH="$HOME/Software/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    export LD_LIBRARY_PATH="$HOME/Software/usr/lib:$LD_LIBRARY_PATH"
fi


# NOTE
# Find out what this means:
# (from GNU/Linux)
# The default umask is set in /etc/profile
# umask 022
