#!/usr/bin/env sh
# filename: profile   (linked from ~/.profile)
# purpose: For setting non-bash-specific configs for shells
#   (eg, `sh` or `bash` invoked as `sh`) and graphical applications(?).


# (from MacOS system)

# Recommended by "brew doctor" [2019-01-08]
#echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
export PATH="/usr/local/sbin:$PATH"

# To include kaggle API
export PATH="/Users/zero/.local/bin:$PATH"
