#!/usr/bin/env bash
# filename: zprofile   (linked as .zprofile)
# purpose: For setting login-shell configs, both non-interactive & interactive.

# A lot of my experimentation started with this article / tutorial:
# https://www.davidculley.com/customizing-the-terminal/

# Non-ZSH-specific login-shell configs are in ~/.profile
source ~/.profile
