#!/usr/bin/env bash
# filename: zshrc   (linked as .zshrc)
# purpose: For setting interactive shell configs.


# Note:
# 1. This config file is executed automatically by zsh for both login and non-
#    login shells (unlike `.bashrc`, which is only auto-executed for non-login).
# 2. So, in `.zprofile` (for login-shells), this file does *not* need to be
#    sourced (unlike in `.bash_profile`, where `.bashrc` *is* sourced *if* the
#    shell is interactive).
# 3. I don't know if this config file has issues like `.bashrc` does with
#    non-interactive remote shells.  Might be worth investigating.


# Source/Execute the following config files:
source ~/.config/zsh/zshrc_omz
source ~/.config/zsh/zshrc_opt
source ~/.config/zsh/zshrc_prompt
source ~/.config/zsh/zshrc_etc

source ~/.bashrc

# For MacOS
if [[ `uname -s` = "Darwin" ]] ; then
  source ~/.config/zsh/zshrc_etc_mac
fi

# For conda / anaconda (on work Dev VM)
if [ -f ~/.config/zsh/zshrc_conda ]; then
  source ~/.config/zsh/zshrc_conda
fi

# Activate zsh packages:
source ~/.config/zsh/pack/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/pack/zsh-autosuggestions/zsh-autosuggestions.zsh
