#!/usr/bin/env bash
# filename: zshrc_opt   (linked from ~/.zshrc_opt)
# purpose: For setting shell options.

# This file is sourced from ~/.zshrc (which is for interactive shells).


# Set the `nullglob` option so list pattern-matching is silent for null matches
setopt nullglob


# vi edit-mode
# Use vi key-bindings (instead of default emacs bindings).
bindkey -v

# Specific custom keybindings placed in `.inputrc`, but apparently I need to
# put them here too.


# Custom Key Bindings
# See documentation for readline; see `bind --help`, `man bind`, `man bindkey`;
# eg, see `bind -p` for all vi functions.

# allow ctrl-l to shift current active prompt to top of screen
bindkey '^k' clear-screen

# allow ctrl-p, ctrl-n for navigate history
#"\C-P": up-history
#"\C-N": down-history
bindkey '^p' up-history
bindkey '^n' down-history

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

# allow backspace (not ctrl-?), ctrl-h, ctrl-w for backward char and word delete
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^b' backward-kill-word
# For "\C-?" and "\C-h", this "fixes" the "problem" of not being able to delete
# old letters when inserting text (so no longer really an "insert"-only mode).

# could set for insert mode only
# set keymap vi-insert
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^l' vi-forward-char
# `vi-forward-char` is equivalent to what one might call "right-arrow"

