#!/usr/bin/env bash
# filename: zshrc   (linked as .zshrc)
# purpose: For setting interactive shell configs.


# Note:
# 1. This config file is executed automatically by zsh for both login and non-
#    login shells (unlike `.bashrc`, which is only auto-executed for non-login).
# 2. So, in `.zprofile` (for login-shells), this file does *not* need to be
#    sourced (unlike in `.bash_profile`, where `.bashrc` *is* sourced *if* the
#    shell is interactive).
# 3. I don't know if this config file has issues like `.bashrc` does with
#    non-interactive remote shells.  Might be worth investigating.


# Source/Execute the following config files:
source ~/.zshrc_omz
source ~/.zshrc_opt
source ~/.zshrc_prompt

source ~/.bashrc_aliases
source ~/.bashrc_etc


# Activate zsh packages:
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

