#!/usr/bin/env bash
# filename: zshrc_opt   (linked from ~/.zshrc_opt)
# purpose: For setting shell options.

# This file is sourced from ~/.zshrc (which is for interactive shells).


# Set the `nullglob` option so list pattern-matching is silent for null matches
setopt nullglob


# vi edit-mode
bindkey -v

# allow ctrl-p, ctrl-n for navigate history (standard behaviour)
#bindkey '^P' up-history
#bindkey '^N' down-history

# allow ctrl-h, ctrl-w, ctrl-? for char and word deletion (standard behaviour)
#bindkey '^?' backward-delete-char
#bindkey '^h' backward-delete-char
#bindkey '^w' backward-kill-word

# allow ctrl-a and ctrl-e to move to beginning/end of line (emacs-style)
#bindkey '^a' beginning-of-line
#bindkey '^e' end-of-line

