;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	keyboard-quit
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-forward-char
	evil-next-line
	evil-set-marker
	evil-visual-char
	))
