#!/usr/bin/env bash
# filename: inputrc   (linked from ~/.inputrc)
# purpose: Set readline configs.


# From reference [1]:
# The GNU Readline library provides a set of functions for use by applications
# that allow users to edit command lines as they are typed in. Both Emacs and vi
# editing modes are available. The Readline library includes additional
# functions to maintain a list of previously-entered command lines, to recall
# and perhaps reedit those lines, and perform csh-like history expansion on
# previous commands.

# May want to move history material from bashrc_etc to here.


# Set universal readline editing mode to vi (rather than emacs)
set editing-mode vi


# References:
# [1] The GNU Readline Library
#     https://tiswww.case.edu/php/chet/readline/rltop.html
